import React, { createContext, useContext, useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import i18n from '../i18n';

export type Language = 'en' | 'es' | 'zh' | 'tl' | 'vi' | 'ar' | 'fr' | 'ko';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    'app.name': 'CityPulse',
    'nav.home': 'Home',
    'nav.activity': 'Activity',
    'nav.action': 'Action',
    'nav.map': 'Map',
    'nav.create': 'Create',
    'auth.login': 'Login',
    'auth.signup': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.logout': 'Logout',
    'profile.points': 'Points',
    'profile.activities': 'Activities',
    'profile.giftcards': 'Gift Cards',
    'incident.report': 'Report Incident',
    'incident.title': 'Incident Title',
    'incident.description': 'Description',
    'incident.category': 'Category',
    'incident.severity': 'Severity',
    'incident.location': 'Location',
    'category.energy': 'Energy & Climate',
    'category.waste': 'Waste & Recycling',
    'category.water': 'Water Conservation',
    'category.air': 'Air Quality',
    'category.transport': 'Transportation',
    'category.green': 'Green Spaces',
    'category.community': 'Community Programs',
    'category.policy': 'Policy & Advocacy',
    'action.take': 'Take Action',
    'action.investigating': 'Investigating',
    'action.monitoring': 'Monitoring',
    'action.resolved': 'Resolved',
    'action.escalated': 'Escalated',
    'donation.title': 'Donations',
    'donation.make': 'Make a Donation',
    'donation.support': 'Support our mission to create positive change',
    'donation.total_raised': 'Total Raised',
    'donation.donors': 'Donors',
    'donation.choose_amount': 'Choose Donation Amount',
    'donation.custom_amount': 'Custom amount',
    'donation.your_name': 'Your name (optional)',
    'donation.your_email': 'Your email (optional)',
    'donation.anonymous': 'Make this donation anonymous',
    'donation.processing': 'Processing...',
    'donation.donate': 'Donate',
    'donation.amount': 'Amount',
    'donation.history': 'Your Donation History',
    'donation.loading': 'Loading your donations...',
    'donation.none': 'No donations yet',
    'donation.first': 'Make your first donation above!',
    'donation.thank_you': 'Thank you for your generous donation!',
    'donation.error.invalid': 'Please enter a valid donation amount',
    'donation.error.minimum': 'Minimum donation is $1',
    'donation.error.stripe': 'Stripe is not configured. Please contact the administrator.',
    'donation.error.failed': 'Failed to create donation',
    'donation.error.general': 'An error occurred while processing your donation',
    'status.completed': 'Completed',
    'status.pending': 'Pending',
    'status.failed': 'Failed',
    'status.refunded': 'Refunded',
    'rewards.title': 'Gift Cards & Rewards',
    'rewards.redeem': 'Redeem Card',
    'preferences.title': 'Preferences',
    'preferences.language': 'Language',
    'map.title': 'Heat Map',
    'map.filter': 'Filter',
    'activity.recent': 'Recent Activity',
    'submit': 'Submit',
    'cancel': 'Cancel',
    'save': 'Save',
    'close': 'Close',
    'loading': 'Loading...',
    'search': 'Search'
  },
  es: {
    'app.name': 'CityPulse',
    'nav.home': 'Inicio',
    'nav.activity': 'Actividad',
    'nav.action': 'Acción',
    'nav.map': 'Mapa',
    'nav.create': 'Crear',
    'auth.login': 'Iniciar Sesión',
    'auth.signup': 'Registrarse',
    'auth.email': 'Correo',
    'auth.password': 'Contraseña',
    'auth.logout': 'Cerrar Sesión',
    'profile.points': 'Puntos',
    'profile.activities': 'Actividades',
    'profile.giftcards': 'Tarjetas de Regalo',
    'incident.report': 'Reportar Incidente',
    'incident.title': 'Título del Incidente',
    'incident.description': 'Descripción',
    'incident.category': 'Categoría',
    'incident.severity': 'Severidad',
    'incident.location': 'Ubicación',
    'category.energy': 'Energía y Clima',
    'category.waste': 'Residuos y Reciclaje',
    'category.water': 'Conservación del Agua',
    'category.air': 'Calidad del Aire',
    'category.transport': 'Transporte',
    'category.green': 'Espacios Verdes',
    'category.community': 'Programas Comunitarios',
    'category.policy': 'Política y Defensa',
    'action.take': 'Tomar Acción',
    'action.investigating': 'Investigando',
    'action.monitoring': 'Monitoreando',
    'action.resolved': 'Resuelto',
    'action.escalated': 'Escalado',
    'donation.title': 'Donaciones',
    'donation.make': 'Hacer una Donación',
    'donation.support': 'Apoya nuestra misión de crear un cambio positivo',
    'donation.total_raised': 'Total Recaudado',
    'donation.donors': 'Donantes',
    'donation.choose_amount': 'Elige el Monto de la Donación',
    'donation.custom_amount': 'Monto personalizado',
    'donation.your_name': 'Tu nombre (opcional)',
    'donation.your_email': 'Tu correo (opcional)',
    'donation.anonymous': 'Hacer esta donación anónima',
    'donation.processing': 'Procesando...',
    'donation.donate': 'Donar',
    'donation.amount': 'Cantidad',
    'donation.history': 'Tu Historial de Donaciones',
    'donation.loading': 'Cargando tus donaciones...',
    'donation.none': 'Aún no hay donaciones',
    'donation.first': '¡Haz tu primera donación arriba!',
    'donation.thank_you': '¡Gracias por tu generosa donación!',
    'donation.error.invalid': 'Por favor ingresa un monto válido',
    'donation.error.minimum': 'La donación mínima es $1',
    'donation.error.stripe': 'Stripe no está configurado. Por favor contacta al administrador.',
    'donation.error.failed': 'Error al crear la donación',
    'donation.error.general': 'Ocurrió un error al procesar tu donación',
    'status.completed': 'Completado',
    'status.pending': 'Pendiente',
    'status.failed': 'Fallido',
    'status.refunded': 'Reembolsado',
    'rewards.title': 'Tarjetas de Regalo y Recompensas',
    'rewards.redeem': 'Canjear Tarjeta',
    'preferences.title': 'Preferencias',
    'preferences.language': 'Idioma',
    'map.title': 'Mapa de Calor',
    'map.filter': 'Filtrar',
    'activity.recent': 'Actividad Reciente',
    'submit': 'Enviar',
    'cancel': 'Cancelar',
    'save': 'Guardar',
    'close': 'Cerrar',
    'loading': 'Cargando...',
    'search': 'Buscar'
  },
  zh: {
    'app.name': 'CityPulse',
    'nav.home': '首页',
    'nav.activity': '活动',
    'nav.action': '行动',
    'nav.map': '地图',
    'nav.create': '创建',
    'auth.login': '登录',
    'auth.signup': '注册',
    'auth.email': '邮箱',
    'auth.password': '密码',
    'auth.logout': '登出',
    'profile.points': '积分',
    'profile.activities': '活动',
    'profile.giftcards': '礼品卡',
    'incident.report': '报告事件',
    'incident.title': '事件标题',
    'incident.description': '描述',
    'incident.category': '类别',
    'incident.severity': '严重程度',
    'incident.location': '位置',
    'category.energy': '能源与气候',
    'category.waste': '废物与回收',
    'category.water': '水资源保护',
    'category.air': '空气质量',
    'category.transport': '交通运输',
    'category.green': '绿色空间',
    'category.community': '社区项目',
    'category.policy': '政策与倡导',
    'action.take': '采取行动',
    'action.investigating': '调查中',
    'action.monitoring': '监控中',
    'action.resolved': '已解决',
    'action.escalated': '已升级',
    'donation.title': '捐款',
    'donation.make': '进行捐赠',
    'donation.support': '支持我们创造积极变化的使命',
    'donation.total_raised': '总筹款',
    'donation.donors': '捐赠者',
    'donation.choose_amount': '选择捐赠金额',
    'donation.custom_amount': '自定义金额',
    'donation.your_name': '您的姓名（可选）',
    'donation.your_email': '您的邮箱（可选）',
    'donation.anonymous': '匿名捐赠',
    'donation.processing': '处理中...',
    'donation.donate': '捐赠',
    'donation.amount': '金额',
    'donation.history': '您的捐赠历史',
    'donation.loading': '加载您的捐赠记录...',
    'donation.none': '暂无捐赠记录',
    'donation.first': '在上方进行您的第一笔捐赠！',
    'donation.thank_you': '感谢您的慷慨捐赠！',
    'donation.error.invalid': '请输入有效的捐赠金额',
    'donation.error.minimum': '最低捐赠金额为 $1',
    'donation.error.stripe': 'Stripe 未配置。请联系管理员。',
    'donation.error.failed': '创建捐赠失败',
    'donation.error.general': '处理您的捐赠时出错',
    'status.completed': '已完成',
    'status.pending': '待处理',
    'status.failed': '失败',
    'status.refunded': '已退款',
    'rewards.title': '礼品卡和奖励',
    'rewards.redeem': '兑换卡',
    'preferences.title': '偏好设置',
    'preferences.language': '语言',
    'map.title': '热力图',
    'map.filter': '筛选',
    'activity.recent': '最近活动',
    'submit': '提交',
    'cancel': '取消',
    'save': '保存',
    'close': '关闭',
    'loading': '加载中...',
    'search': '搜索'
  },
  tl: {
    'app.name': 'CityPulse',
    'nav.home': 'Home',
    'nav.activity': 'Aktibidad',
    'nav.action': 'Aksyon',
    'nav.map': 'Mapa',
    'nav.create': 'Lumikha',
    'auth.login': 'Mag-login',
    'auth.signup': 'Mag-sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.logout': 'Mag-logout',
    'profile.points': 'Puntos',
    'profile.activities': 'Mga Aktibidad',
    'profile.giftcards': 'Mga Gift Card',
    'incident.report': 'Mag-ulat ng Insidente',
    'incident.title': 'Titulo ng Insidente',
    'incident.description': 'Deskripsyon',
    'incident.category': 'Kategorya',
    'incident.severity': 'Kalubhaan',
    'incident.location': 'Lokasyon',
    'category.energy': 'Enerhiya at Klima',
    'category.waste': 'Basura at Pag-recycle',
    'category.water': 'Konserbasyon ng Tubig',
    'category.air': 'Kalidad ng Hangin',
    'category.transport': 'Transportasyon',
    'category.green': 'Berdeng Espasyo',
    'category.community': 'Mga Programang Komunidad',
    'category.policy': 'Patakaran at Adbokasya',
    'action.take': 'Kumilos',
    'action.investigating': 'Sinisiyasat',
    'action.monitoring': 'Sinusubaybayan',
    'action.resolved': 'Nalutas',
    'action.escalated': 'Naitaas',
    'donation.title': 'Mga Donasyon',
    'donation.donate': 'Mag-donate',
    'donation.amount': 'Halaga',
    'rewards.title': 'Mga Gift Card at Gantimpala',
    'rewards.redeem': 'I-redeem ang Card',
    'preferences.title': 'Mga Kagustuhan',
    'preferences.language': 'Wika',
    'map.title': 'Heat Map',
    'map.filter': 'I-filter',
    'activity.recent': 'Kamakailang Aktibidad',
    'submit': 'Ipasa',
    'cancel': 'Kanselahin',
    'save': 'I-save',
    'close': 'Isara',
    'loading': 'Naglo-load...',
    'search': 'Maghanap'
  },
  vi: {
    'app.name': 'CityPulse',
    'nav.home': 'Trang chủ',
    'nav.activity': 'Hoạt động',
    'nav.action': 'Hành động',
    'nav.map': 'Bản đồ',
    'nav.create': 'Tạo mới',
    'auth.login': 'Đăng nhập',
    'auth.signup': 'Đăng ký',
    'auth.email': 'Email',
    'auth.password': 'Mật khẩu',
    'auth.logout': 'Đăng xuất',
    'profile.points': 'Điểm',
    'profile.activities': 'Hoạt động',
    'profile.giftcards': 'Thẻ quà tặng',
    'incident.report': 'Báo cáo sự cố',
    'incident.title': 'Tiêu đề sự cố',
    'incident.description': 'Mô tả',
    'incident.category': 'Danh mục',
    'incident.severity': 'Mức độ nghiêm trọng',
    'incident.location': 'Vị trí',
    'category.energy': 'Năng lượng & Khí hậu',
    'category.waste': 'Chất thải & Tái chế',
    'category.water': 'Bảo tồn nước',
    'category.air': 'Chất lượng không khí',
    'category.transport': 'Giao thông',
    'category.green': 'Không gian xanh',
    'category.community': 'Chương trình cộng đồng',
    'category.policy': 'Chính sách & Vận động',
    'action.take': 'Hành động',
    'action.investigating': 'Đang điều tra',
    'action.monitoring': 'Đang giám sát',
    'action.resolved': 'Đã giải quyết',
    'action.escalated': 'Đã leo thang',
    'donation.title': 'Quyên góp',
    'donation.donate': 'Quyên góp',
    'donation.amount': 'Số tiền',
    'rewards.title': 'Thẻ quà tặng & Phần thưởng',
    'rewards.redeem': 'Đổi thẻ',
    'preferences.title': 'Tùy chọn',
    'preferences.language': 'Ngôn ngữ',
    'map.title': 'Bản đồ nhiệt',
    'map.filter': 'Lọc',
    'activity.recent': 'Hoạt động gần đây',
    'submit': 'Gửi',
    'cancel': 'Hủy',
    'save': 'Lưu',
    'close': 'Đóng',
    'loading': 'Đang tải...',
    'search': 'Tìm kiếm'
  },
  ar: {
    'app.name': 'CityPulse',
    'nav.home': 'الرئيسية',
    'nav.activity': 'النشاط',
    'nav.action': 'العمل',
    'nav.map': 'الخريطة',
    'nav.create': 'إنشاء',
    'auth.login': 'تسجيل الدخول',
    'auth.signup': 'إنشاء حساب',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.logout': 'تسجيل الخروج',
    'profile.points': 'النقاط',
    'profile.activities': 'الأنشطة',
    'profile.giftcards': 'بطاقات الهدايا',
    'incident.report': 'الإبلاغ عن حادث',
    'incident.title': 'عنوان الحادث',
    'incident.description': 'الوصف',
    'incident.category': 'الفئة',
    'incident.severity': 'الخطورة',
    'incident.location': 'الموقع',
    'category.energy': 'الطاقة والمناخ',
    'category.waste': 'النفايات وإعادة التدوير',
    'category.water': 'الحفاظ على المياه',
    'category.air': 'جودة الهواء',
    'category.transport': 'النقل',
    'category.green': 'المساحات الخضراء',
    'category.community': 'برامج المجتمع',
    'category.policy': 'السياسة والدعوة',
    'action.take': 'اتخاذ إجراء',
    'action.investigating': 'قيد التحقيق',
    'action.monitoring': 'قيد المراقبة',
    'action.resolved': 'تم الحل',
    'action.escalated': 'تم التصعيد',
    'donation.title': 'التبرعات',
    'donation.make': 'تقديم تبرع',
    'donation.support': 'ادعم مهمتنا لإحداث تغيير إيجابي',
    'donation.total_raised': 'إجمالي المبلغ المجموع',
    'donation.donors': 'المتبرعون',
    'donation.choose_amount': 'اختر مبلغ التبرع',
    'donation.custom_amount': 'مبلغ مخصص',
    'donation.your_name': 'اسمك (اختياري)',
    'donation.your_email': 'بريدك الإلكتروني (اختياري)',
    'donation.anonymous': 'جعل هذا التبرع مجهولاً',
    'donation.processing': 'جاري المعالجة...',
    'donation.donate': 'تبرع',
    'donation.amount': 'المبلغ',
    'donation.history': 'سجل تبرعاتك',
    'donation.loading': 'جاري تحميل تبرعاتك...',
    'donation.none': 'لا توجد تبرعات بعد',
    'donation.first': 'قدم تبرعك الأول أعلاه!',
    'donation.thank_you': 'شكراً لك على تبرعك السخي!',
    'donation.error.invalid': 'يرجى إدخال مبلغ تبرع صالح',
    'donation.error.minimum': 'الحد الأدنى للتبرع هو $1',
    'donation.error.stripe': 'Stripe غير مكون. يرجى الاتصال بالمسؤول.',
    'donation.error.failed': 'فشل إنشاء التبرع',
    'donation.error.general': 'حدث خطأ أثناء معالجة تبرعك',
    'status.completed': 'مكتمل',
    'status.pending': 'قيد الانتظار',
    'status.failed': 'فشل',
    'status.refunded': 'تم الاسترداد',
    'rewards.title': 'بطاقات الهدايا والمكافآت',
    'rewards.redeem': 'استبدال البطاقة',
    'preferences.title': 'التفضيلات',
    'preferences.language': 'اللغة',
    'map.title': 'خريطة الحرارة',
    'map.filter': 'تصفية',
    'activity.recent': 'النشاط الأخير',
    'submit': 'إرسال',
    'cancel': 'إلغاء',
    'save': 'حفظ',
    'close': 'إغلاق',
    'loading': 'جاري التحميل...',
    'search': 'بحث'
  },
  fr: {
    'app.name': 'CityPulse',
    'nav.home': 'Accueil',
    'nav.activity': 'Activité',
    'nav.action': 'Action',
    'nav.map': 'Carte',
    'nav.create': 'Créer',
    'auth.login': 'Connexion',
    'auth.signup': 'Inscription',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.logout': 'Déconnexion',
    'profile.points': 'Points',
    'profile.activities': 'Activités',
    'profile.giftcards': 'Cartes-cadeaux',
    'incident.report': 'Signaler un incident',
    'incident.title': "Titre de l'incident",
    'incident.description': 'Description',
    'incident.category': 'Catégorie',
    'incident.severity': 'Gravité',
    'incident.location': 'Emplacement',
    'category.energy': 'Énergie et climat',
    'category.waste': 'Déchets et recyclage',
    'category.water': "Conservation de l'eau",
    'category.air': "Qualité de l'air",
    'category.transport': 'Transport',
    'category.green': 'Espaces verts',
    'category.community': 'Programmes communautaires',
    'category.policy': 'Politique et plaidoyer',
    'action.take': 'Prendre action',
    'action.investigating': 'En cours de vérification',
    'action.monitoring': 'Surveillance',
    'action.resolved': 'Résolu',
    'action.escalated': 'Escaladé',
    'donation.title': 'Dons',
    'donation.donate': 'Faire un don',
    'donation.amount': 'Montant',
    'rewards.title': 'Cartes-cadeaux et récompenses',
    'rewards.redeem': 'Échanger la carte',
    'preferences.title': 'Préférences',
    'preferences.language': 'Langue',
    'map.title': 'Carte thermique',
    'map.filter': 'Filtrer',
    'activity.recent': 'Activité récente',
    'submit': 'Soumettre',
    'cancel': 'Annuler',
    'save': 'Sauvegarder',
    'close': 'Fermer',
    'loading': 'Chargement...',
    'search': 'Rechercher'
  },
  ko: {
    'app.name': 'CityPulse',
    'nav.home': '홈',
    'nav.activity': '활동',
    'nav.action': '액션',
    'nav.map': '지도',
    'nav.create': '생성',
    'auth.login': '로그인',
    'auth.signup': '가입하기',
    'auth.email': '이메일',
    'auth.password': '비밀번호',
    'auth.logout': '로그아웃',
    'profile.points': '포인트',
    'profile.activities': '활동',
    'profile.giftcards': '기프트 카드',
    'incident.report': '사건 신고',
    'incident.title': '사건 제목',
    'incident.description': '설명',
    'incident.category': '카테고리',
    'incident.severity': '심각도',
    'incident.location': '위치',
    'category.energy': '에너지 및 기후',
    'category.waste': '폐기물 및 재활용',
    'category.water': '물 보존',
    'category.air': '공기 질',
    'category.transport': '교통',
    'category.green': '녹지 공간',
    'category.community': '커뮤니티 프로그램',
    'category.policy': '정책 및 옹호',
    'action.take': '조치 취하기',
    'action.investigating': '조사 중',
    'action.monitoring': '모니터링 중',
    'action.resolved': '해결됨',
    'action.escalated': '에스컬레이션됨',
    'donation.title': '기부',
    'donation.donate': '기부하기',
    'donation.amount': '금액',
    'rewards.title': '기프트 카드 및 보상',
    'rewards.redeem': '카드 사용',
    'preferences.title': '환경설정',
    'preferences.language': '언어',
    'map.title': '히트 맵',
    'map.filter': '필터',
    'activity.recent': '최근 활동',
    'submit': '제출',
    'cancel': '취소',
    'save': '저장',
    'close': '닫기',
    'loading': '로딩 중...',
    'search': '검색'
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const { t: i18nT } = useTranslation();
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    i18n.changeLanguage(language);
    document.documentElement.lang = language;

    if (language === 'ar') {
      document.documentElement.dir = 'rtl';
    } else {
      document.documentElement.dir = 'ltr';
    }
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    const legacyTranslation = translations[language]?.[key];
    if (legacyTranslation) return legacyTranslation;

    return i18nT(key);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}

export const LANGUAGE_OPTIONS = [
  { code: 'en' as Language, name: 'English', flag: '🇺🇸' },
  { code: 'es' as Language, name: 'Español', flag: '🇪🇸' },
  { code: 'zh' as Language, name: '中文', flag: '🇨🇳' },
  { code: 'tl' as Language, name: 'Tagalog', flag: '🇵🇭' },
  { code: 'vi' as Language, name: 'Tiếng Việt', flag: '🇻🇳' },
  { code: 'ar' as Language, name: 'العربية', flag: '🇸🇦' },
  { code: 'fr' as Language, name: 'Français', flag: '🇫🇷' },
  { code: 'ko' as Language, name: '한국어', flag: '🇰🇷' }
];
